---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1d92fp6gk7klp0g6rlz8ngs3wclsw7etnplz2d3j5v594m67m4ctqzputd5
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1d92fp6gk7klp0g6rlz8ngs3wclsw7etnplz2d3j5v594m67m4ctqzputd5
