---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: internal-ips
  namespace: networking
spec:
  ipWhiteList:
    sourceRange:
      - 10.0.0.0/8
      - 192.168.2.0/16
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: internal-only
  namespace: networking
spec:
  chain:
    middlewares:
      - name: internal-ips
