---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-cluster
  namespace: flux-system
spec:
  interval: 10m
  ref:
    branch: main
  url: https://github.com/ipedrazas/alacasa.lab
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-cluster
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/base
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-cluster
